# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('_HelpWithZnewgen2_rcpparma_hello_world', PACKAGE = 'HelpWithZnewgen2')
}

rcpparma_outerproduct <- function(x) {
    .Call('_HelpWithZnewgen2_rcpparma_outerproduct', PACKAGE = 'HelpWithZnewgen2', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_HelpWithZnewgen2_rcpparma_innerproduct', PACKAGE = 'HelpWithZnewgen2', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_HelpWithZnewgen2_rcpparma_bothproducts', PACKAGE = 'HelpWithZnewgen2', x)
}

Znew_gen2 <- function(U, Z, g, cols, n, q, d, pBigMat, J) {
    invisible(.Call('_HelpWithZnewgen2_Znew_gen2', PACKAGE = 'HelpWithZnewgen2', U, Z, g, cols, n, q, d, pBigMat, J))
}

